# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rasem 0.7.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rasem"
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ahmed Eldawy", "Vytis Valentinavi\u{10d}ius"]
  s.date = "2015-08-28"
  s.description = "  This gem allows you to describe your images using ruby code.\n  You can use rasem to draw complex images using small portions of ruby code\n"
  s.email = "eldawy@cs.umn.edu"
  s.executables = ["rasem"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/rasem",
    "lib/rasem.rb",
    "lib/rasem/application.rb",
    "lib/rasem/download_documentation.rb",
    "lib/rasem/svg_documentation.rb",
    "lib/rasem/svg_image.rb",
    "spec/defs_spec.rb",
    "spec/gradient_spec.rb",
    "spec/path_spec.rb",
    "spec/rasem_spec.rb",
    "spec/spec_helper.rb",
    "spec/transform_spec.rb"
  ]
  s.homepage = "http://github.com/aseldawy/rasem"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "A gem to generate images from ruby files"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.2"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.6.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.2"])
      s.add_dependency(%q<simplecov>, ["~> 0.6.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.10.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.2"])
    s.add_dependency(%q<simplecov>, ["~> 0.6.4"])
  end
end

